### ISSUE TITLE
support for anchor links within a page

### ISSUE THREAD

**Issue by reco** [estrattonbailey/operator#13]
`http://server.com/path#id-of-element` should scroll to the element on that page.

**Comment by estrattonbailey** [comment]
@reco thanks for the issue! We're talking native browser behavior here, right?

Part of the reason for that is I originally wanted to leave route and `History` handling to the user, to allow for hash routing and other tricks. I'm thinking that's a very niche use case, so perhaps it's time to rethink.

I think we'll need to consider how to keep `state` in sync, but ignore hashes so that the browser can handle them. I'll have a think on this. Let me know if you have any ideas! Would be happy to help with a pull request :)

**Comment by estrattonbailey** [comment]
@reco decided to jump right into this, actually.

When you get a sec, can you have at [what I just pushed up](https://github.com/estrattonbailey/operator/tree/hash#hash-anchors) and let me know what you think? 

You can install from that version using `npm i operator@dev --save`.

I think this is a good solve that retains flexibility. Users are still free to handle routing, and handling scroll on the user end is simple enough that I hope it shouldn't cause too much headache. Would love to hear your thoughts!

**Comment by estrattonbailey** [comment]
Published in `v1.6.0`
